apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: testing-server-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: testing-server
    spec:
      volumes:
        - name: secret-volume
          secret:
            secretName: testing-server-secret
      containers:
      - name: testing-server
        image: rutsky/testing-server:v0.0.3
        args:
        - --hostname=0.0.0.0
        - --port=8080
        - --htpasswd-file=/srv/secret/htpasswd
        - --token-secret-file=/srv/secret/token.secret
        - --worker-ssh-known-hosts=/srv/secret/known_hosts
        - --worker-ssh-key=/srv/secret/id_rsa
        - -l=DEBUG
        env:
        - name: SENTRY_DSN
          valueFrom:
            secretKeyRef:
              name: testing-server-secret
              key: sentry_dsn
        - name: TESTING_SERVER_TRAC_XMLRPC_URI
          valueFrom:
            secretKeyRef:
              name: testing-server-secret
              key: trac_xmlrpc_uri
        - name: TESTING_SERVER_POSTGRES_URI
          valueFrom:
            secretKeyRef:
              name: testing-server-secret
              key: postgres_uri
        - name: TESTING_SERVER_SVN_URI
          valueFrom:
            secretKeyRef:
              name: testing-server-secret
              key: svn_uri
        - name: TESTING_SERVER_SVN_USERNAME
          valueFrom:
            secretKeyRef:
              name: testing-server-secret
              key: svn_username
        - name: TESTING_SERVER_SVN_PASSWORD
          valueFrom:
            secretKeyRef:
              name: testing-server-secret
              key: svn_password
        - name: TESTING_SERVER_WORKER_SSH_HOST
          valueFrom:
            secretKeyRef:
              name: testing-server-secret
              key: worker-ssh-host
        - name: TESTING_SERVER_WORKER_SSH_USERNAME
          valueFrom:
            secretKeyRef:
              name: testing-server-secret
              key: worker-ssh-username
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: secret-volume
          readOnly: true
          mountPath: /srv/secret
