apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: testing-server-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: testing-server
    spec:
      containers:
      - name: testing-server
        image: rutsky/testing-server:dev
        ports:
        - containerPort: 8080
